export const ACADEMIC_CATALOG_SERVICE = 'ACADEMIC_CATALOG_SERVICE';
export const ACADEMIC_MANAGEMENT_SERVICE = 'ACADEMIC_MANAGEMENT_SERVICE';
export const INSCRIPCIONES_SERVICE = 'INSCRIPCIONES_SERVICE';
